export const ActionTypes = {
  ON_CLICK_BOOK_LINK: "ON_CLICK_BOOK_LINK",
  ON_TYPE_SEARCH_BAR: "ON_TYPE_SEARCH_BAR",
  SET_DETAIL_BOOK: "SET_DETAIL_BOOK",
  SET_LIST_BOOK: "SET_LIST_BOOK",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
}
